### PR TITLE
Fix install-sh and parsing string to int

### PR DESCRIPTION
**Pull request by moozeq**
Changes:
- made `install-sh` executable which fixes error with running `./configure`
- parsing string to integer was taking into account `;` character causing segmentation fault

### CODE REVIEW

**Comment by ChrisCreevey** [comment]
Thanks for suggesting these changes. I've been looking into the integer parsing issue you raised and I can't replicate it. Could you provide an example input tree which generates the error you report? 
The semicolon is caught on line 3236 as sometimes the final close parenthesis in the tree may have a label and it is necessary to know that in that case the character ';' is to be expected. Chris.

**Comment by moozeq** [comment]
Hi, sorry that I didn't answer right away but I didn't notice Your reply. I built `clann` with debug symbols and found the issue with `gdb` so I don't really know if it should be caught before or something, but it's causing a segmentation fault.

To replicate:

file `cmds`:
```
execute; hs swap=spr weight=equal
```

file `nj-all-trees.ph`: https://pastebin.com/raw/DXX6ZLXS

command:
`clann -n -c cmds nj-all-trees.ph`

output:
```
(...)
Heuristic search progress indicator:
Repetition 1 of 10:=[1]    45010 segmentation fault  ./clann -n -c cmds nj-all-trees.ph
```

Edit: With suggested changes in parsing, issue doesn't occur.

**Comment by ChrisCreevey** [comment]
Hi,
So I notice from your file that there are both single and multi-copy genes trees in the input. This is likely what is causing the unexpected behaviour. The underlying assumption of the supertree approach that all the input trees are single copy. If you want to use the basic `hs` approach in clann you can identify and delete all the multi-copy gene trees using the command `deletetrees multicopy`. 
In your data set the input data summary detail the number of single and multicopy genes in your dataset:
```
	Number of single copy trees:	346
	number of multicopy trees:	154
```
Once I deleted the multi-copy trees from your data, the `hs` command worked without problem. This has highlighted that I need to add a warning for these commands if the data is not all single-copy and perhaps provide the option to automatically delete any multicopy gene trees.

If you have any questions, or if the behaviour persists even after following the above details let me know.
Chris.

**Comment by moozeq** [comment]
Ok, now I understand the cause of this issue and your solution seems reasonable. Thank you for your time.

**Pull request closed without merging**
